"""The Dashboard's own to-do list (tasks people write, not generated by the system) and the
"ya lo vi" marks on its alerts."""
from datetime import datetime

from sqlalchemy import Column, Date, DateTime, ForeignKey, Integer, String, Text, UniqueConstraint
from sqlalchemy.orm import relationship

from app.db.base_class import Base

PRIORITIES = ("alta", "normal", "baja")
PRIORITY_LABELS = {"alta": "Alta", "normal": "Normal", "baja": "Baja"}


class Task(Base):
    __tablename__ = "tasks"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(200), nullable=False)
    # Free text; links written here can be opened from the Dashboard.
    description = Column(Text, nullable=True)
    due_date = Column(Date, nullable=False, index=True)
    priority = Column(String(10), nullable=False, default="normal", server_default="normal")
    # Who has to do it. Admin and supervisor can assign tasks to someone else.
    assignee_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    created_by_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    done_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    assignee = relationship("User", foreign_keys=[assignee_id])
    created_by = relationship("User", foreign_keys=[created_by_id])


class AlertAck(Base):
    """A person marked an alert as seen: it moves to their "Pendientes" until it gets worse
    (new items that were not there when they marked it) or it is solved."""
    __tablename__ = "alert_acks"
    __table_args__ = (UniqueConstraint("user_id", "key", name="uq_alert_ack_user_key"),)

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    key = Column(String(60), nullable=False)
    # JSON list of the alert's items when it was marked (invoice ids, days, ...).
    items = Column(Text, nullable=False, default="[]")
    acked_at = Column(DateTime, default=datetime.utcnow)
